title: Cryptography Advent Calendar 2017
description: 暗号学の各種トピックについてだらだら書くよ

baseurl: "/crypto-ac-2017" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://s01.info" # change this to the base hostname & protocol for your site

google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: "sylph01"
image: /thumbnail-jumbo.png
twitter:
  username: s01
#  site: